services:
  postgres:
    image: postgres:15-alpine
    container_name: ekofin_db
    # .env dosyasının yerini açıkça gösteriyoruz
    env_file:
      - ./apps/api/.env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-ekofin}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: ekofin_api
    # API konteynerine de .env dosyasını veriyoruz
    env_file:
      - ./apps/api/.env
    environment:
      - DB_HOST=postgres
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: